"""Dump a human-readable manifest of all chunks in the Chroma index.

Writes `data/chunk_manifest.md`: every chunk id with its section title
and a ~100-char preview of the chunk body. Useful when writing
retrieval-set entries by hand, so you can pick a chunk id and write a
query that should hit it, without having to read the source rst files.
"""

from __future__ import annotations

import logging
from pathlib import Path

import chromadb

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]
CHROMA_DIR = ROOT / ".chroma"
COLLECTION = "pytest_docs"
OUT = ROOT / "data" / "chunk_manifest.md"
PREVIEW_CHARS = 120


def preview(text: str) -> str:
    body = text.split("\n\n", 1)[1] if text.startswith("# ") and "\n\n" in text else text
    body = " ".join(body.split())
    return body[:PREVIEW_CHARS] + ("..." if len(body) > PREVIEW_CHARS else "")


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    coll = client.get_collection(COLLECTION)
    data = coll.get(include=["documents", "metadatas"])

    rows = list(zip(data["ids"], data["documents"], data["metadatas"], strict=True))
    by_source: dict[str, list] = {}
    for cid, doc, meta in rows:
        by_source.setdefault(meta["source"], []).append((cid, doc, meta))

    lines = [
        "# Chunk manifest",
        "",
        f"Total chunks: {len(rows)}. Generated by `dump_manifest.py`.",
        "",
        "Format: each row is `chunk_id` | section | preview.",
        "",
    ]
    for src in sorted(by_source):
        items = by_source[src]
        lines.append(f"## {src} ({len(items)} chunks)")
        lines.append("")
        for cid, doc, meta in sorted(items, key=lambda r: r[0]):
            lines.append(f"- `{cid}` | **{meta['section']}** | {preview(doc)}")
        lines.append("")

    OUT.write_text("\n".join(lines))
    logger.info("wrote %s (%d chunks across %d files)", OUT, len(rows), len(by_source))


if __name__ == "__main__":
    main()
